name: PUSH - Check and Build
on:
  push:
    branches:
      - main
      #- PA-1042

jobs:
  compute_diff:
    name: Compute diff on folders
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed folders
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          dir_names: true
          dir_names_exclude_current_dir: true
          dir_names_max_depth: 2
          matrix: true
          quotepath: false
          files: |
            ddbk-to-json/**

      - name: Filter directories
        id: filter-dirs
        shell: bash
        env:
          changed_libs: "${{ steps.changed-files.outputs.all_changed_files }}"
        run: |
            echo $changed_libs

    outputs:
      changed_dirs: ${{ steps.changed-files.outputs.all_changed_files }}

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: compute_diff
    if: ${{ needs.compute_diff.outputs.changed_dirs != '[]' }}
    strategy:
      matrix:
        dir: ${{ fromJSON(needs.compute_diff.outputs.changed_dirs) }}
    defaults:
      run:
        working-directory: ${{ matrix.dir }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '11'
          server-id: github
          settings-path: ${{ github.workspace }}
      
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Check if Module Generates NAR
        id: check-nar
        run: |
          if grep -q "<packaging>nar</packaging>" pom.xml; then
            echo "GENERATES_NAR=true" >> $GITHUB_ENV
          else
            echo "GENERATES_NAR=false" >> $GITHUB_ENV
          fi

      - name: Copy Build Outputs
        if: env.GENERATES_NAR == 'true'
        run: |
          mkdir -p artifacts
          cp target/*.nar artifacts/

      - name: Upload Artifact
        if: env.GENERATES_NAR == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: artifacts
