name: PR - Check and Build
on:
  pull_request: # Trigger pipeline on PR activity

jobs:
  find-modules:
    name: Find Modules
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      folders: ${{ steps.modules.outputs.folders }}
    env:
      WORKING_DIRECTORY: ddbk-to-json
    steps:
      - uses: actions/checkout@v4
      - name: List Sub-Folders
        id: modules
        uses: kmanimaran/list-folder-action@v4
        with:
          path: ${{ env.WORKING_DIRECTORY }}
      - name: finded modules
        shell: bash
        run: |
            echo ${{ steps.modules.outputs.folders }}

  build:
    name: Build and Upload Artifacts
    runs-on: ubuntu-latest
    needs: find-modules
    timeout-minutes: 30
    env:
      WORKING_DIRECTORY: ddbk-to-json
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build with Maven
      run: mvn clean install