name: Deploy all modules on Github
on:
  push:
    branches:
      - PA-1042

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    defaults:
      run:
        #working-directory: ddbk-to-json
        working-directory: ddbk-to-json/nifi-ddbk-to-json-processor
        #working-directory: ddbk-to-json/nifi-ddbk-to-json-nar

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: debug
        run: |
          pwd
          ls -la

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '11'
          server-id: github
          settings-path: ${{ github.workspace }}
      
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Set up Maven settings
        run: |
          mkdir -p ~/.m2
          echo "<settings>
                  <servers>
                    <server>
                      <id>github</id>
                      <username>${{ secrets.GITHUB_ACTOR }}</username>
                      <password>${{ secrets.GITHUB_TOKEN }}</password>
                    </server>
                  </servers>
                </settings>" > ~/.m2/settings.xml

      - name: Build with Maven
        run: mvn clean install -X
        
      - name: Deploy to GitHub Packages
        run: mvn deploy -X
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
