name: Build and Upload Artifacts

on:
  push:
    branches:
      - PA-1042

jobs:
  find-modules:
    name: Find Modules
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      folders: ${{ steps.modules.outputs.folders }}

    steps:
      - uses: actions/checkout@v4

      - name: List Sub-Folders
        id: modules
        uses: kmanimaran/list-folder-action@v4
        with:
          path: ddbk-to-json

      - name: Folders
        shell: bash
        run: |
            echo ${{ steps.modules.outputs.folders }}

  build:
    runs-on: ubuntu-latest
    needs: find-modules
    timeout-minutes: 30
    defaults:
      run:
        working-directory: "ddbk-to-json"

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Build with Maven
      run: mvn clean install

    - name: Check for .nar files and upload artifacts
      id: check
      shell: bash
      env:
        folders: ${{ needs.find-modules.outputs.folders}}
      run: |
        mkdir -p artifacts
        IFS=',' read -ra ADDR <<< "${folders//[\[\]\" ]/}"
        for dir in "${ADDR[@]}"; do
          for file in "${dir}/target/"*.nar; do
            if [ -f "$file" ]; then
              echo "Found .nar file in ${dir}, creating and uploading artifact..."
              mv "$file" "artifacts/"
              echo "GENERATES_NAR=true" >> $GITHUB_ENV
            fi
          done
        done

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      if: env.GENERATES_NAR == 'true'
      with:
        name: build-artifacts
        path: ddbk-to-json/artifacts/**/*

    - uses: actions/download-artifact@v4
      with:
        name: build-artifacts
