name: Deploy all modules on Github
on:
  push:
    branches:
      - PA-1042

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    #defaults:
    #  run:
    #    #working-directory: ddbk-to-json
    #    working-directory: ddbk-to-json/nifi-ddbk-to-json-processors
    #    #working-directory: ddbk-to-json/nifi-ddbk-to-json-nar

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: debug
        run: |
          pwd
          ls -la

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '11'
          server-id: github
          #settings-path: ${{ github.workspace }}

      - name: Set up Maven settings
        run: |
          mkdir -p ~/.m2
          echo "<settings xmlns=\"http://maven.apache.org/SETTINGS/1.0.0\"
                        xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"
                        xsi:schemaLocation=\"http://maven.apache.org/SETTINGS/1.0.0
                                            http://maven.apache.org/xsd/settings-1.0.0.xsd\">
                  <activeProfiles>
                    <activeProfile>github</activeProfile>
                  </activeProfiles>
                  <profiles>
                    <profile>
                      <id>github</id>
                      <repositories>
                        <repository>
                          <id>central</id>
                          <url>https://repo1.maven.org/maven2</url>
                        </repository>
                        <repository>
                          <id>github</id>
                          <url>https://maven.pkg.github.com/pagopa/pdnd-nifi-custom-nars</url>
                          <snapshots>
                            <enabled>true</enabled>
                          </snapshots>
                        </repository>
                      </repositories>
                    </profile>
                  </profiles>
                  <servers>
                    <server>
                      <id>github</id>
                      <username>${{ secrets.GITHUB_ACTOR }}</username>
                      <password>${{ secrets.GITHUB_TOKEN }}</password>
                    </server>
                  </servers>
                </settings>" > ~/.m2/settings.xml
      
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      #- name: Set up Maven settings
      #  run: |
      #    mkdir -p ~/.m2
      #    echo "<settings>
      #            <servers>
      #              <server>
      #                <id>github</id>
      #                <username>${{ secrets.GITHUB_ACTOR }}</username>
      #                <password>${{ secrets.GITHUB_TOKEN }}</password>
      #              </server>
      #            </servers>
      #          </settings>" > ~/.m2/settings.xml
#
      - name: Build with Maven
        run: mvn clean install -X
        
      - name: Deploy to GitHub Packages
        run: mvn deploy -X
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
